### ISSUE TITLE
Purchased your book. I wonder how to connect Firebase with Stripe (or other payment system) without backend

### ISSUE THREAD

**Issue by hughred22** [learning-ionic/Chapter-9#1]
I am looking for solution to has ONLY front end solution to charge people using Stripe or PayPal with only Firebase and AngualrJS. No Node.js or any backend (I am only a front end developer). Could you point me to the right direction?

**Comment by arvindr21** [comment]
Why are you trying to connect Firebase with Stripe? Are planning to store the transaction details?

**Comment by hughred22** [comment]
I want to charge user with Stripe or pay user with Stripe (building a TaskRabbit or Uber Clone). I do not want to build an backend (why I use Firebase). I also hear a BaaS called Stamplay. But I already built my app with Firebase, Firebase Authorization, and managing user there using your amazing book. Just one thing is lacking - payment system. I do not know Node.js / Express / Sail and not planning to learn them as I am a front end developer.

**Comment by arvindr21** [comment]
Stripe provides a web based checkout https://stripe.com/docs/tutorials/checkout (not sure if you need a server to validate the processing). If you do need one, you can create simple static hosted pages on Firebase itself (https://www.firebase.com/docs/hosting/guide/deploying.html). Inside these static pages, you can again interact with Firebase to process the payment redirects, if needed.

Other options are
- Paypal Cordova plugin - https://github.com/paypal/PayPal-Cordova-Plugin 
- In app purchases - https://github.com/j3k0/cordova-plugin-purchase

Let me know what do you think.

**Comment by hughred22** [comment]
I believe the web based checkout need nodejs to generate a token. I have no idea how to use a static page to interact with Stripe. All in all, I would love to have an tutorial about interact with Stripe with ONLY Ionic, AngularJS and Firebase. And I can not find any on the net. I also google around PayPal Cordova Plugin and/or Braintree - there is NO tutorials and good instruction on how to integrate that with Ionic / AngularJS. All of them need Ruby or Node. I just need a very simple solution, people hit pay in Ionic App,  open a form for input (can be Braintree dropin or Stripe quick checkout), hit pay return a successful object and unique identifier to store back in Firebase to show user is paid...And an example of doing that will be greatly appreciated and great addition to the book. 
BTW, in app purchase is way too expensive for iOs. So it is out of question.

**Comment by hughred22** [comment]
I think I will just create a simple node.js backend to deal with the Stripe task. I asked Firebase as well and there are no easy option to do that.

**Comment by jasan-s** [comment]
@hughred22 i'm in a similar boat, developing a react redux app with firebase as main database. I can't seem to figure out how to integrate stripe & twilio with it. i was also told to run my own node scripts on heroku that interact with stripe or other api's but not sure how to do that. Did yo ever get it working, if so any tips guide or tutorial recommandations? I was also recently told about firebase queue but also not sure how to use that
